server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3307/wanted}
    username: ${db.username:root}
    password: ${db.password:root}

  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

app:
  jwt:
    secret: ${secret:77d1b474a0920ab13e44a05170117cf0e809bad5c554d19020a95b45e9e2fb95893b8b149382e294d78fdb8e5aa2ae266b5797d985f5dc127366d2a50ec3938e}
    expired-in:  ${expired:1800000} # [ms]
