env:
  DB_PASSWORD: root

name: build-test
on:
  push:
    branches: [develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set Up MySQL
        run : |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE wantedtest;' -uroot -proot

      - name: Set Up JDK 17
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Spring boot Build
        uses: gradle/gradle-build-action@main
        with:
          gradle-version: wrapper
          arguments: build -x test --no-daemon
